//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.30 at 12:46:05 PM CET 
//


package se.uhr.simone.restbucks.boundary.representation;

import jakarta.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public final class OrderEventRepresentation {

	public String id;
	public Link link;

	public OrderEventRepresentation() {
	}
	public OrderEventRepresentation(String id, Link link) {
		this.id = id;
		this.link = link;
	}

	@Override
	public String toString() {
		return "OrderEventRepresentation[" + "id=" + id + ", " + "link=" + link + ']';
	}

}
