# For use with vscode rest client
@host = http://localhost:8080

### Feed
GET {{host}}/feed/recent

### List orders
GET {{host}}/order

### Add order
POST {{host}}/order

Coffee

### Load DB from orders.txt

POST {{host}}/admin/database
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="name"

orders.txt
------boundary
Content-Disposition: form-data; name="content"
Content-Type: text/plain; charset=utf-8

< ./orders.txt
------boundary--


### Drop DB

DELETE {{host}}/admin/database


### Answer with strange status code

PUT {{host}}/admin/rs/response/code/global
Content-Type: text/plain

400


### Answer normally

DELETE {{host}}/admin/rs/response/code/global


### Answer with strange status code and body

PUT {{host}}/admin/rs/response/body
Content-Type: application/json

{
    "path": "/order",
    "code": "401",
    "body": ""
}

### Answer with strange status code and body

DELETE {{host}}/admin/rs/response/body
Content-Type: text/plain

/order


### Block feed

PUT {{host}}/admin/feed/block

### un-block feed

DELETE {{host}}/admin/feed/block